### ISSUE TITLE
LI Validação assincrona: Sequenciador e canvas MVP

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2023.2-Dnit-DOC#11]
- [x] Ajustar o sequenciador conforme potenciais ajustes realizados no Revisão de valor e UX;
- [x] Ajustar o canvas MVP conforme potenciais ajustes anteriores;
- [x] Solicitar e notificar a validação do sequenciador;
- [x] Solicitar e notificar a validação do canvas MVP;
- [x] Confirmar a definição do MVP.

**Comment by RafaelBP02** [comment]
Sequenciador foi validado na reunião com os clientes do DNIT no dia 09/10/2023
