### ISSUE TITLE
Treinamento C#

### ISSUE THREAD

**Issue by thiagohdaqw** [fga-eps-mds/2023.2-Dnit-DOC#3]
- [x] Slides
- [x] Exemplos
- [x] Apresentação pra MDS

**Comment by thiagohdaqw** [comment]
[TreinamentoCSharp.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbitEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3badc93013a35ee15c0eaeb8ea209a543879f309/TreinamentoCSharp.zip)

**Comment by DanielPortods** [comment]
- [Apresentação para o treinamento de C#](https://www.canva.com/design/DAFuFppTIHo/mYDZXDOFSG-8qj4c8o4hog/edit?utm_content=DAFuFppTIHo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by thiagohdaqw** [comment]
https://youtu.be/63SJzTDIaNo
