### ISSUE TITLE
Treinamento .NET

### ISSUE THREAD

**Issue by thiagohdaqw** [fga-eps-mds/2023.2-Dnit-DOC#4]
- [x] Slides
- [x] Códigos exemplos
- [x] Apresentação pra MDS

**Comment by yudi-azvd** [comment]
Apresentação feita no dia 27/09/2023

[Video no YouTube](https://www.youtube.com/watch?v=tMB0GwntJtA)

Repositório exemplo: [yudi-azvd/MinhasEscolas](https://github.com/yudi-azvd/MinhasEscolas)

[Slides](https://github.com/yudi-azvd/MinhasEscolas/blob/main/treinamento-dotnet.pdf) (link direto, mas já tá no repo)
