### ISSUE TITLE
Configuração do sonar

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2023.2-Dnit-DOC#46]

**Comment by yudi-azvd** [comment]
Tá dando erro nos pushes do UpsService: https://github.com/fga-eps-mds/2023.2-Dnit-UpsService/actions/runs/6427344945

**Comment by wagnermc506** [comment]
Sonar configurado em todos os repositórios:
- UsuárioService: https://sonarcloud.io/project/overview?id=fga-eps-mds_2023.2-Dnit-UsuarioService
- EscolaService: https://sonarcloud.io/project/overview?id=fga-eps-mds_2023.2-Dnit-EscolaService
- UpsService: https://sonarcloud.io/project/overview?id=fga-eps-mds_2023.2-Dnit-UpsService
- Front: https://sonarcloud.io/project/overview?id=fga-eps-mds_2023.2-Dnit-Front

**Comment by thiagohdaqw** [comment]
@wagnermc506, acho que precisa modificar esse action pra fazer o upload das metricas do sonar no repositorio de doc
![image](https://github.com/fga-eps-mds/2023.2-Dnit-DOC/assets/54081877/3ffda925-2dea-491c-b5cc-f0fac10f7c55)

**Comment by yudi-azvd** [comment]
@wagnermc506 E agora tá dando outro erro

![image](https://github.com/fga-eps-mds/2023.2-Dnit-DOC/assets/37981839/40f67dd6-458c-428f-9129-2b88ad6d3448)

**Comment by thiagohdaqw** [comment]
@wagnermc506 pode postar aqui o url da metrica usada pra deixar registrado?

**Comment by wagnermc506** [comment]
A URL de métricas é: 

https://sonarcloud.io/api/measures/component_tree?metricKeys=complexity,functions,ncloc,reliability_rating,security_rating,comment_lines_density,files,duplicated_lines_density,test_errors,test_failures,test_success_density&component=fga-eps-mds_2023.2-Dnit-UsuarioService&ps=500

Todos os repositórios estão usando o mesmo conjunto de métricas. Para mudar o repositório, é necessário mudar o parâmetro `component`:
- UsuarioService: fga-eps-mds_2023.2-Dnit-UsuarioService
- EscolaService: fga-eps-mds_2023.2-Dnit-EscolaService
- UpsService: fga-eps-mds_2023.2-Dnit-UpsService
- Front: fga-eps-mds_2023.2-Dnit-Front

**Comment by wagnermc506** [comment]
A URL das métricas foi atualizada a partir da Release 1. Segue as URLs atualizadas:

### Usuário Service

https://sonarcloud.io/api/measures/component_tree?metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,tests,test_errors,test_failures,test_execution_time,security_rating&component=fga-eps-mds_2023.2-Dnit-UsuarioService&ps=500

### Escola Service

https://sonarcloud.io/api/measures/component_tree?metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,tests,test_errors,test_failures,test_execution_time,security_rating&component=fga-eps-mds_2023.2-Dnit-EscolaService&ps=500

### Ups Service

https://sonarcloud.io/api/measures/component_tree?metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,tests,test_errors,test_failures,test_execution_time,security_rating&component=fga-eps-mds_2023.2-Dnit-UpsService&ps=500

### Front

https://sonarcloud.io/api/measures/component_tree?metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,tests,test_errors,test_failures,test_execution_time,security_rating&component=fga-eps-mds_2023.2-Dnit-Front&ps=500
