### ISSUE TITLE
Treinamento React

### ISSUE THREAD

**Issue by thiagohdaqw** [fga-eps-mds/2023.2-Dnit-DOC#5]
- [x] Slides
- [x] Exemplos
- [x] Apresentação pro MDS
- [x] ....

**Comment by victorhugo21** [comment]
- [Apresentação para o treinamento de React](https://www.canva.com/design/DAFuwM9XEhA/rveCfrcotYT_UCt3mcF5oQ/edit?utm_content=DAFuwM9XEhA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by RafaelBP02** [comment]
Video do treinamento disponível em breve

**Comment by RafaelBP02** [comment]
Link para o vídeo: https://youtu.be/SVbs7G0zISA
