### ISSUE TITLE
Autenticação e autorização do sistema

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2023.2-Dnit-DOC#63]
Atualmente, qualquer um pode acessar as funcionalidades da aplicação, ou seja, não está verificando a autorização e autenticação das rotas. Dessa forma, é necessário adicionar essa melhoria

#64 
#65 

## Tarefas
- [x] Modelagem do banco para os perfis e permissões (Perfil e Permissão)
- [x] Autenticar o usuário com o login
- [x] Proteger as rotas para os usuários autenticados
- [x] Proteger as rotas pela autorização do usuário (permissão)

## Critérios de aceitação
- [ ] ...

**Comment by thiagohdaqw** [comment]
Como a arquitetura do sistema é um microserviço, a autenticação e autorização é mais complexa, uma vez que é preciso manter a consistência entre os serviços. O `UsuarioService`, atualmente, tem a responsabilidade do login, apesar de verificar se o usuário está logado entre as requisições. Dessa forma, as permissões também constaram nesse serviço. Os outros serviços irão consultar o usuario service para verificar a autenticação e autorização daquela dada requisição. Para melhorar a eficiencia, o uso de cache será utilizado

**Comment by thiagohdaqw** [comment]
Foi implementado utilizando o JWT, que assina o token digitalmente. Dessa forma os serviços não precisam requisitar ao usuário service a cada requisição, pois a chave privada da assinatura é compartilhada entre os serviços e é possivel realizar a verificação. Além disso, as permissões são enviadas pelo token
