### ISSUE TITLE
US 1: Gerenciar perfis

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2023.2-Dnit-DOC#64]
## Descrição
Eu, como administrador do DNIT, quero gerenciar os perfis de usuário do sistema para configurar possíveis mudanças da Organização.

## Tarefas

- [x] Protótipo
- [x] Testes
- [x] Implementar autenticação
- [x] Implementar autorização
- [x] Autorizar rotas
- [x] Criar perfil com nome e permissões

Exemplos e sugestões de permissão: 
- Calcular UPS
- Criar (escola, ação, sinistro, etc)
- Editar (escola, ação, sinistro, etc)
- Excluir (escola, ação, sinistro, etc)

## Critérios de aceitação

- [x] Na Dashboard, ao clicar em "Gerenciar perfis", o usuário deve visualizar a tabela de perfis com nome, quantidade de usuários associados ao perfil, breve descrição
- [x] Ao clicar no botão "Criar perfil", usuário preenche no campo perfil o nome do novo perfil e as permissões que ele deseja atribuir a ele
- [x] Ao clicar no botão "Visualizar perfil" (ícone do olho), pode visualizar nome e permissões do perfil sem poder editá-los
- [x] Ao clicar no botão "Editar perfil" (ícone do lápis), pode editar nome do perfil e habilitar ou desabilitar as suas permissões 
- [x] Ao clicar no botão "Excluir perfil" (ícone lixeira), usuário vai confirmar essa ação no modal

## Links

Protótipo no FIGMA: <https://www.figma.com/proto/zyNXXEdSgbYnXQorSQPRgA/Prot%C3%B3tipos-de-Alta-Fidelidade-DNIT?type=design&node-id=1444-5903&t=JxiBxAwLj0ypYwdG-0&scaling=min-zoom&starting-point-node-id=1444%3A7018&show-proto-sidebar=1>

Vídeo explicativo: <https://youtu.be/NotkBUoGv3c>

**Comment by NayaraDNIT** [comment]
OBSERVAÇÕES NAYARA:
- Não localizei no protótipo o botão "Visualizar perfil" (ícone do olho);
- Ao final, quando salvo as alterações e ele me devolve mensagem de sucesso ou erro, está direcionando para a página de gerenciamento de usuários. Não deveria ser para a própria página de gerenciamento de perfis?
