### ISSUE TITLE
US 2: Gerenciar os diferentes tipos de usuários do sistema 

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2023.2-Dnit-DOC#65]
## Descrição
Eu, como administrador do DNIT, quero gerenciar os diferentes tipos de usuários do sistema para garantir a organização no acesso.

## Tarefas
- [x] Protótipo
- [x] Testes
- [x] Listar usuários 
- [x] Filtrar por nome
- [x] Filtrar por UF
- [x] Filtrar por perfil
- [x] Alterar perfil de um usuário
- [x] Enviar resultado da operação (sucesso ou falha)
- [x] Correção: quando um perfil é excluído, todos os usuários com o perfil excluído devem ser alterados para o perfil **Básico**.

## Critérios de aceitação

- [x] Usuário pode visualizar a lista de usuários 
- [x] Ao clicar no campo de filtro de "Nome", a tabela é filtrada pelo nome do usuário
- [x] Ao clicar no campo de filtro de "UF", a tabela é filtrada pela UF do usuário
- [x] Ao clicar no campo de filtro de "Perfil", a tabela é filtrada pelo perfil do usuário
- [x] Ao clicar no campo de filtro de "Município", a tabela é filtrada pelo município do usuário
- [x] Usuário pode alterar perfil de um usuário
- [x] Usuário recebe alerta de sucesso ao clicar no botão de confirmar alteração de perfil

## Observações
Como ainda não existe gerenciamento de empresa (criação, edição, etc), o filtro por empresas _ainda_ não será implementado nessa US. O filtro por empresa será implementado futuramente.

## Links

Protótipo do FIGMA: <https://www.figma.com/proto/zyNXXEdSgbYnXQorSQPRgA/Prot%C3%B3tipos-de-Alta-Fidelidade-DNIT?type=design&node-id=1444-5903&t=JxiBxAwLj0ypYwdG-0&scaling=min-zoom&starting-point-node-id=1444%3A5905&show-proto-sidebar=1>

Vídeo explicativo: <https://youtu.be/f9wbUbn5vCc>

**Comment by NayaraDNIT** [comment]
Acho que podemos excluir o botão de criar perfil dessa aba. Provavelmente a pessoa que irá gerenciar os usuários (gestor estratégico) será diferente daquela que irá gerenciar os perfis (apenas admin). A ideia é dificultar a criação de novos perfis, deixar essa demanda centralizada para que não se crie de forma aleatória

**Comment by NayaraDNIT** [comment]
Não identifiquei a opção de filtro por email, apesar de estar descrito nos critérios de aceitação. Mas também não acho que essa busca específica seja relevante. Pode excluir dos critérios de aceitação e deixar o protótipo como está

**Comment by NayaraDNIT** [comment]
Não identifiquei a opção de filtro por email, apesar de estar descrito nos critérios de aceitação. Mas também não acho que essa busca específica seja relevante. Pode excluir dos critérios de aceitação e deixar o protótipo como está

**Comment by NayaraDNIT** [comment]
Seria interessante poder extrair esses dados de usuários em forma de tabela, para fazer gráficos e análises, criar listas de emails etc.

**Comment by NayaraDNIT** [comment]
Além da UF, também é importante eu saber o município de lotação desse usuário

**Comment by RafaelBP02** [comment]
> Seria interessante poder extrair esses dados de usuários em forma de tabela, para fazer gráficos e análises, criar listas de emails etc.

Olá nayara. Estamos cientes desse assunto e ele será tratado na US9 #75
