### ISSUE TITLE
Lean Inception

### ISSUE THREAD

**Issue by RafaelBP02** [fga-eps-mds/2023.2-Dnit-DOC#7]
### Reunião inicial (13/10)

- [x] Plano de ação inicial;
- [x] Planilha de estimativa de custos.

### Reuniões de adaptação e revisões (14/09, 15/09 e 16/09)

 - [x] Visão do Produto
 - [x] É, Não é, Faz, Não faz
 - [x] Objetivos do Produto
 - [x] Personas
 - [x] Jornada do Usuário
 - [x] Brainstorming de Funcionalidades
 - [x] Revisão técnica, de Negócio e de UX
 - [x] Sequenciador
 - [x] Canvas MVP

**Comment by DanielPortods** [comment]
- [Planilha de estimativa inicial de custo do projeto](https://docs.google.com/spreadsheets/d/1XazIV9hg0pYdSUX7uJrYIJ-JptCoF08b77tn3C1I800/edit?usp=sharing)

**Comment by DanielPortods** [comment]
A equipe concluiu em conjunto as atividades referentes ao Lean Inception nas referidas reuniões. Na reunião semanal ocorrida no dia 18/09 foram validados com o PO os artefatos:

- Visão do Produto;
- É, Não é, Faz, Não faz;
- Objetivos do Produto.

Dessa forma, os demais serão validados assincronamente durante a semana.
