### ISSUE TITLE
[Doc] Protótipo de baixa fidelidade da US06

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2023.2-Dnit-DOC#82]
**Descrição**
Deve ser realizada a prototipação em baixa fidelidade do funcionalidade F13 levantada durante a aplicação do Lean Inception, a qual trata do custo logístico das ações.

**Tarefas :** 
- [ ] Criar o protótipo de baixa fidelidade.

**Comment by RafaelBP02** [comment]
As discuções dessa issue continuam na issue #74
